import Database.Star_server;


/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Sidiq
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        btn_log_Off.setVisible(false);
        jMenuBar1.setVisible(false);
        




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btn_login = new usu.widget.ButtonGlass();
        btn_log_Off = new usu.widget.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MasterData = new javax.swing.JMenu();
        TambahMobil = new javax.swing.JMenuItem();
        TambahUser = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        LaporanMobil = new javax.swing.JMenuItem();
        LaporanTransaksi = new javax.swing.JMenuItem();
        Profil = new javax.swing.JMenu();
        Keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Server");
        setBackground(new java.awt.Color(51, 255, 51));
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 1220, 891));

        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginoke.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_login.setGlassColor(new java.awt.Color(0, 0, 0));
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        btn_log_Off.setForeground(new java.awt.Color(255, 255, 255));
        btn_log_Off.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_off copy.png"))); // NOI18N
        btn_log_Off.setText("Log Off");
        btn_log_Off.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_log_Off.setGlassColor(new java.awt.Color(51, 51, 51));
        btn_log_Off.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_log_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_OffActionPerformed(evt);
            }
        });
        getContentPane().add(btn_log_Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        jLabel1.setBackground(new java.awt.Color(153, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homeoke.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 300, 880));

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 51));

        MasterData.setText("Master Data");

        TambahMobil.setText("Tambah Pegawai");
        TambahMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahMobilActionPerformed(evt);
            }
        });
        MasterData.add(TambahMobil);

        TambahUser.setText("Tambah User");
        TambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUserActionPerformed(evt);
            }
        });
        MasterData.add(TambahUser);

        jMenuBar1.add(MasterData);

        Transaksi.setText("Transaksi Cuti");
        Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransaksiMouseClicked(evt);
            }
        });
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");

        LaporanMobil.setText("Laporan Pegawai");
        LaporanMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanMobilActionPerformed(evt);
            }
        });
        Laporan.add(LaporanMobil);

        LaporanTransaksi.setText("Laporan Cuti");
        LaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanTransaksiActionPerformed(evt);
            }
        });
        Laporan.add(LaporanTransaksi);

        jMenuBar1.add(Laporan);

        Profil.setText("Profil");
        Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilMouseClicked(evt);
            }
        });
        Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilActionPerformed(evt);
            }
        });
        jMenuBar1.add(Profil);

        Keluar.setText("Keluar");
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Keluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        //     jDesktopPane1.removeAll();
        //     jDesktopPane1.repaint();
        dispose();
        Login_server fm = new Login_server();
        fm.setVisible(true);
        //jDesktopPane1.add(fm);


    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_log_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_OffActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        btn_login.setVisible(true);
        btn_log_Off.setVisible(false);
        btn_log_Off.setVisible(false);

        

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_log_OffActionPerformed

    private void LaporanMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanMobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Laporan_Pegawai lm = new Laporan_Pegawai();
        lm.setVisible(true);
        jDesktopPane1.add(lm);           // TODO add your handling code here:
    }//GEN-LAST:event_LaporanMobilActionPerformed

    private void LaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanTransaksiActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Laporan_Cuti lp = new Laporan_Cuti();
        lp.setVisible(true);
        jDesktopPane1.add(lp); // TODO add your handling code here:
    }//GEN-LAST:event_LaporanTransaksiActionPerformed

    private void TambahMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahMobilActionPerformed
       jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Pegawai fl = new Form_Pegawai();
        fl.setVisible(true);
        jDesktopPane1.add(fl); // TODO add your handling code here:
    }//GEN-LAST:event_TambahMobilActionPerformed

    private void TambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUserActionPerformed
       jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_user fu = new Form_user();
        fu.setVisible(true);
        jDesktopPane1.add(fu); // TODO add your handling code here:
    }//GEN-LAST:event_TambahUserActionPerformed

    private void ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_ProfilActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiActionPerformed

    private void TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Cuti ft = new Form_Cuti();
        ft.setVisible(true);
        jDesktopPane1.add(ft);        // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiMouseClicked

    private void ProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        About_ a = new About_();
        a.setVisible(true);
        jDesktopPane1.add(a);         // TODO add your handling code here:
    }//GEN-LAST:event_ProfilMouseClicked

    private void KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void admin() {


        btn_log_Off.setVisible(true);
        btn_login.setVisible(false);
        jMenuBar1.setVisible(true);

        

    }

    public void user() {

        btn_log_Off.setVisible(true);
        btn_login.setVisible(false);
        jMenuBar1.setVisible(true);

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Keluar;
    public static javax.swing.JMenu Laporan;
    public static javax.swing.JMenuItem LaporanMobil;
    public static javax.swing.JMenuItem LaporanTransaksi;
    public static javax.swing.JMenu MasterData;
    public static javax.swing.JMenu Profil;
    public static javax.swing.JMenuItem TambahMobil;
    public static javax.swing.JMenuItem TambahUser;
    public static javax.swing.JMenu Transaksi;
    public static usu.widget.ButtonGlass btn_log_Off;
    public static usu.widget.ButtonGlass btn_login;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
